"""empty message

Revision ID: 84e1856d3fc7
Revises: bac4050e3aeb
Create Date: 2019-12-13 22:03:35.128514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84e1856d3fc7'
down_revision = 'bac4050e3aeb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('education', sa.String(length=140), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'education')
    # ### end Alembic commands ###
